

services:
  postgres:
    image: postgres
    container_name: nest_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passs
      POSTGRES_DB: restraunt-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
